# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e8e6a13f61e355ff71345441c4f4ae553c7af3048ab76fda89e888208180881f49ace567d10ae55a0823d9b1ddb5008554461de51384e51a3097f72a198759b0

test:
  secret_key_base: 4920db8a1dbfa31e47a5b0f2261263324f3f27e12492369f0a07943e7888b4b6900b9fe7e97c5016aec720a999676a7405ee67862ad69328892db4324d8fdd34

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
